const {start,root}=require('./visual_fixture.cjs'),fs=require('fs'),path=require('path'),assert=require('assert'),cp=require('child_process');
(async()=>{const{browser,p,server,snapshot}=await start(),checks=[],sent=[],errors=[];const check=(s,b)=>{assert(b,s);checks.push(s)};p.on('pageerror',e=>errors.push(e.message));
const select=async(name,label)=>{await p.locator('select[name='+name+']').evaluate(s=>s.parentElement.querySelector('.choice-trigger').click());await p.getByRole('option',{name:label,exact:true}).click();};
try{
 await p.route('**/api/cards/save',r=>{sent.push(r.request().postDataJSON());return r.fulfill({json:{status:'saved'}})});
 await p.route('**/api/launch',r=>{sent.push(r.request().postDataJSON());return r.fulfill({json:{status:'queued',message:'Test'}})});
 await p.evaluate(()=>cardEditor(state.apps[0],state.profile.cards[0]));await p.getByText('Pantalla y tamaño al abrir',{exact:true}).click();check('Cards default to bring to front',await p.locator('[name=activation]').inputValue()==='front');await select('activation','Dejar que Windows decida');await p.locator('#card-form [type=submit]').click();await p.waitForFunction(()=>!document.querySelector('#modal').open);check('Card save transmits Windows choice',sent.at(-1).activation==='windows');
 await p.evaluate(()=>launchConfigured({...state.profile.cards[0],activation:'windows'}));check('Direct card launch sends saved choice',sent.at(-1).activation==='windows');
 await p.evaluate(()=>launchConfigured({...state.profile.cards[0],activation:'windows',layout:{monitor:'ask',mode:'maximized'}}));check('Monitor prompt preserves activation',await p.locator('[name=activation]').inputValue()==='windows');await select('activation','Traer al frente');await p.locator('#launch-layout-form [type=submit]').click();await p.waitForFunction(()=>!document.querySelector('#modal').open);check('Monitor prompt sends edited activation',sent.at(-1).activation==='front'&&sent.at(-1).layout.mode==='maximized');
 await p.evaluate(()=>stepEditor(-1,'launch',{type:'launch',appId:'roblox',activation:'windows',layout:{monitor:'primary',mode:'maximized'}}));check('Routine editor shows saved policy',await p.locator('[name=activation]').inputValue()==='windows');await select('type','Mover una app ya abierta');check('Move steps have no foreground setting',await p.locator('[name=activation]').count()===0);await select('type','Abrir aplicación');check('Switching types preserves activation',await p.locator('[name=activation]').inputValue()==='windows');await select('activation','Traer al frente');await p.locator('#step-form [type=submit]').click();check('Saving step preserves activation',await p.evaluate(()=>routineDraft.at(-1).activation==='front'));await p.locator('[data-action=edit-step]').last().click();check('Reopening step keeps front policy',await p.locator('[name=activation]').inputValue()==='front');
 await select('type','Controlar música');check('Music has no foreground setting',await p.locator('[name=activation]').count()===0);
 await p.evaluate(()=>{$('#modal').close();state.jobs=[{name:'Jugar bobox',status:'failed',step:1,total:2,message:'Error visible',results:[{status:'failed',message:'No aceptó maximizar'}]}];page='scenes';render()});check('A failed first step explicitly explains second step was not executed',(await p.locator('.job-row').innerText()).includes('El paso siguiente no se ejecutó'));
 await p.evaluate(()=>{state.capabilities.launchForeground=false;cardEditor(state.apps[0],state.profile.cards[0])});check('Old receiver does not advertise unsupported choice',await p.locator('[name=activation]').count()===0);await p.getByText('Pantalla y tamaño al abrir',{exact:true}).click();check('Old receiver shows update explanation',(await p.locator('#card-form').innerText()).includes('Actualiza Eddy Deck en Windows'));
 check('No JavaScript errors',errors.length===0);
 const hashes=JSON.parse(cp.execFileSync(path.join(root,'.build/venv/Scripts/python.exe'),['-c','import json;from scripts.package_evidence import product_sources;print(json.dumps(product_sources()))'],{cwd:root,encoding:'utf8'}));fs.writeFileSync(path.join(root,'artifacts/beta10-launch-ui.json'),JSON.stringify({passed:true,count:checks.length,checks,sourceHashes:hashes,scope:'Production UI with isolated requests; card/routine/one-time launch/save and old receiver behavior.'},null,2));console.log(JSON.stringify({passed:true,count:checks.length}));
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
