const {chromium}=require('playwright');
const fs=require('fs'),path=require('path');
(async()=>{
  const runtime=JSON.parse(fs.readFileSync(path.join(process.env.EDDY_DECK_TEST_DATA||path.resolve('.build/dev-data'),'test-runtime.json'),'utf8'));
  const browser=await chromium.launch({channel:'msedge',headless:true});
  const context=await browser.newContext({viewport:{width:1280,height:1000},locale:'es-MX'});
  await context.addInitScript(value=>sessionStorage.setItem('eddy-token',value),runtime.localToken);
  const page=await context.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto('http://127.0.0.1:47989/');
  await page.getByRole('heading',{name:'Mis accesos'}).waitFor();
  await page.screenshot({path:'.build/desktop-ui.png',fullPage:true});
  await page.locator('#side-nav').getByRole('button',{name:'Biblioteca'}).click();
  await page.getByRole('searchbox',{name:'Buscar aplicaciones'}).fill('Opera');
  await page.getByRole('button',{name:'Agregar Navegador Opera GX',exact:true}).click();
  await page.locator('[name="name"]').fill('Prueba de URL');
  await page.locator('[name="url"]').fill('https://example.com/');
  await page.getByRole('button',{name:'Agregar botón',exact:true}).click();
  await page.getByText('Prueba de URL',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Configurar Prueba de URL',exact:true}).click();
  if(await page.locator('[name="url"]').inputValue()!=='https://example.com/')throw Error('La URL no persistió');
  await page.getByRole('button',{name:'Quitar botón'}).click();
  await page.locator('#side-nav').getByRole('button',{name:'Mi PC',exact:true}).click();
  await page.getByRole('button',{name:'Suspender Descansa el equipo hasta que lo despiertes.'}).click();
  await page.getByRole('button',{name:'Volver',exact:true}).click();
  await page.setViewportSize({width:412,height:915});
  await page.locator('#bottom-nav').getByRole('button',{name:'Inicio',exact:true}).click();
  await page.locator('[data-action="launch-card"]').first().hover();
  await page.mouse.down();await page.waitForTimeout(650);await page.mouse.up();
  await page.getByRole('heading',{name:'Personalizar botón'}).waitFor();
  await page.getByRole('button',{name:'Cerrar',exact:true}).click();
  await page.waitForTimeout(4400);
  await page.screenshot({path:'.build/mobile-ui.png',fullPage:true});
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
  if(overflow)throw Error('Desbordamiento horizontal móvil');
  if(errors.length)throw Error(errors.join('\n'));
  console.log(JSON.stringify({status:'passed',checks:['UI de escritorio y móvil','agregar y guardar URL','quitar botón de prueba','confirmación de energía sin ejecutarla','sin errores JavaScript','sin desbordamiento horizontal']}));
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
