// Production UI with isolated transport. These are not claims about physical hardware.
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert'),cp=require('child_process');
const root=path.resolve(__dirname,'..');
(async()=>{
 const cfg=JSON.parse(fs.readFileSync(path.join(root,'.build/v2-test-data/test-runtime.json'))),checks=[],sent=[],errors=[];
 const browser=await chromium.launch({channel:'msedge',headless:true}),p=await browser.newPage({viewport:{width:412,height:915}});
 const check=(name,ok)=>{assert(ok,name);checks.push(name);console.log(name)},close=async()=>{if(await p.locator('#choice-dialog').isVisible())await p.keyboard.press('Escape');await p.locator('[data-action=close-modal]').first().click()};
 p.on('pageerror',e=>errors.push(e.message));
 try{
  await p.addInitScript(t=>sessionStorage.setItem('eddy-token',t),cfg.localToken);await p.goto('http://127.0.0.1:48089');await p.getByRole('heading',{name:'Hola, Eddy.'}).waitFor();await p.evaluate(()=>clearInterval(pollTimer));await p.waitForFunction(()=>!loading);
  const snapshot=await p.evaluate(()=>structuredClone(state)),id='session:'+'a'.repeat(32);snapshot.capabilities.mediaSessions=true;
  snapshot.media={aimp:true,state:'paused',volume:89,tidal:{state:'paused',running:true},autoTarget:id,players:[{id,name:'Media Player',state:'playing',controls:{play:false,pause:true,stop:false,next:true,previous:false}}]};
  await p.route('**/api/state',r=>r.fulfill({json:snapshot}));await p.route('**/api/media',r=>{sent.push(r.request().postDataJSON());return r.fulfill({json:{status:'completed',message:'Isolated fixture'}})});await p.evaluate(()=>load(true));
  check('Home identifies the actual Auto player',await p.locator('.mini-music strong').innerText()==='Media Player');await p.locator('.mini-music button').click();check('Home sends explicit Auto pause',sent.at(-1).action==='pause'&&sent.at(-1).target==='system');
  snapshot.media.players[0].name='OperaSoftware.OperaGXWebBrowser.'+'1234567890'.repeat(8);await p.evaluate(()=>load(true));for(const width of [320,412]){await p.setViewportSize({width,height:915});check('Long player identifiers do not widen Home or hide navigation at '+width+'px',await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.querySelector('#bottom-nav').getBoundingClientRect().bottom<=innerHeight));}snapshot.media.players[0].name='Media Player';await p.evaluate(()=>load(true));
  await p.locator('#bottom-nav [data-nav=music]').click();await p.locator('#media-target').selectOption(id);await p.locator('.large-play').click();check('Selected player receives pause, not another player',sent.at(-1).target===id&&sent.at(-1).action==='pause');
  check('Unsupported previous is disabled while next remains enabled',await p.locator('[data-media=previous]').isDisabled()&&await p.locator('[data-media=next]').isEnabled());await p.getByRole('button',{name:'Pausar',exact:true}).click();check('Secondary control uses supported pause instead of unsupported stop',sent.at(-1).action==='pause');
  await p.locator('#media-target').focus();await p.locator('#media-target').evaluate(e=>e.dataset.fixture='open-picker');await p.evaluate(()=>load(true));check('Polling preserves the focused player selector instead of dismissing its native popup',await p.locator('#media-target').getAttribute('data-fixture')==='open-picker');await p.locator('#media-target').evaluate(e=>e.blur());
  snapshot.media.players[0].name='<img src=x onerror="window.injected=true">';await p.evaluate(()=>load(true));check('Player label is text in Music, never executable markup',await p.locator('.player h2 img').count()===0&&await p.locator('.player h2').innerText()===snapshot.media.players[0].name);await p.locator('#bottom-nav [data-nav=home]').click();check('Player label is also escaped on Home',await p.locator('.mini-music strong img').count()===0&&await p.evaluate(()=>window.injected)===undefined);await p.locator('#bottom-nav [data-nav=music]').click();
  snapshot.media.players=[];await p.evaluate(()=>load(true));check('Disappeared player remains selected with controls disabled',await p.locator('#media-target').inputValue()===id&&await p.locator('.large-play').isDisabled()&&await p.locator('.player .text-button').isDisabled());
  await p.locator('#media-target').selectOption('aimp');await p.locator('#aimp-volume').focus();await p.locator('#aimp-volume').evaluate(e=>{e.value='37';e.dispatchEvent(new Event('input',{bubbles:true}));e.dataset.fixture='same-node'});snapshot.media.volume=11;await p.evaluate(()=>load(true));check('Polling does not replace or reset a volume slider being edited',await p.locator('#aimp-volume').inputValue()==='37'&&await p.locator('#aimp-volume').getAttribute('data-fixture')==='same-node');
  await p.locator('#aimp-volume').dispatchEvent('change');await p.waitForFunction(()=>document.activeElement?.id!=='aimp-volume');check('Slider sends the final selected value to AIMP',sent.at(-1).value===37&&sent.at(-1).target==='aimp');
  await p.evaluate(()=>stepEditor());await p.locator('#step-app-search').fill('no-existing-app-fixture-718236');check('Empty routine search clears the old hidden choice and blocks submit',await p.locator('#step-app').inputValue()===''&&!(await p.locator('#step-form').evaluate(f=>f.checkValidity())));await close();
  const app=snapshot.apps.find(a=>a.browser)||snapshot.apps[1];await p.evaluate(id=>stepEditor(-1,'launch',{type:'launch',appId:id,layout:{monitor:'right',mode:'maximized'},ifOpen:'reuse'}),app.id);await p.locator('[name=ifOpen]').selectOption('launch');await p.locator('[name=mode]').selectOption('left-half');await p.locator('#step-type').selectOption('window');check('Changing step kind preserves the selected app and unsaved window layout',await p.locator('#step-app').inputValue()===app.id&&await p.locator('[name=mode]').inputValue()==='left-half');await p.locator('#step-type').selectOption('launch');check('Returning to launch preserves existing-window policy',await p.locator('[name=ifOpen]').inputValue()==='launch');await close();
  await p.evaluate(()=>stepEditor(-1,'media',{type:'media',target:'tidal',action:'pause'}));await p.locator('#step-type').selectOption('wait');await p.locator('[name=seconds]').fill('4');await p.locator('#step-type').selectOption('media');check('Media draft survives a round trip through a wait step',await p.locator('[name=target]').inputValue()==='tidal'&&await p.locator('[name=action]').inputValue()==='pause');await p.locator('[name=target]').selectOption('windows');check('Raw Windows keys do not offer explicit play or pause',await p.locator('[name=action] option[value=pause]').evaluate(o=>o.disabled)&&await p.locator('[name=action]').inputValue()==='toggle');await close();
  await p.evaluate(()=>stepEditor(-1,'launch',{type:'launch',appId:'missing-fixture',layout:{}}));check('Missing app in a saved routine requires a new selection',await p.locator('#step-app').inputValue()===''&&!(await p.locator('#step-form').evaluate(f=>f.checkValidity())));await close();
  const card={id:'missing-test-card',appId:'missing-fixture',name:'App ausente de prueba',color:'peach'};snapshot.profile.cards.push(card);await p.locator('#bottom-nav [data-nav=home]').click();await p.evaluate(()=>load(true));
  await p.route('**/api/cards/delete',r=>{snapshot.profile.cards=snapshot.profile.cards.filter(c=>c.id!==card.id);return r.fulfill({json:{status:'completed'}})});
  await p.locator('[data-action=edit-card][data-id=missing-test-card]').click();check('Missing app still opens a removal editor',await p.locator('[data-action=delete-card]').isVisible());await p.locator('[data-action=delete-card]').click();await p.locator('#modal').waitFor({state:'hidden'});await p.locator('[data-id=missing-test-card]').first().waitFor({state:'detached'});check('Removing a missing app actually removes its card from the isolated panel',await p.locator('[data-id=missing-test-card]').count()===0);
  await p.locator('[data-action=repair-pc]').click();check('Receiver repair explains what it restarts before action',await p.locator('#modal').innerText().then(t=>t.includes('otras aplicaciones permanecen abiertas')));await close();
  await p.locator('[data-action=repair-files]').click();check('File repair retains user data and does not reboot Windows',await p.locator('#modal').innerText().then(t=>t.includes('No reinicia Windows')));await close();
  check('No JavaScript runtime exceptions',errors.length===0);
  const sourceHashes=JSON.parse(cp.execFileSync(path.join(root,'.build/venv/Scripts/python.exe'),['-c','import json;from scripts.package_evidence import product_sources;print(json.dumps(product_sources()))'],{cwd:root,encoding:'utf8'}));fs.writeFileSync(path.join(root,'artifacts/beta9-media-ui-tests.json'),JSON.stringify({passed:true,count:checks.length,checks,sourceHashes,scope:'Production HTML/JS in Edge; synthetic state and media transport. Physical phone tests separate.'},null,2));
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
