// Browser interaction tests on production UI; all PC responses are isolated fixtures.
const {start,root}=require('./visual_fixture.cjs'),fs=require('fs'),path=require('path'),assert=require('assert'),cp=require('child_process');
(async()=>{const{browser,p,server,snapshot,dir}=await start(),checks=[],errors=[],sent=[];p.on('pageerror',e=>errors.push(e.message));const check=(name,ok)=>{assert(ok,name);checks.push(name);console.log(name);};
 const open=async name=>{await p.locator('#modal select'+name).evaluate(s=>s.parentElement.querySelector('.choice-trigger').click());await p.locator('#choice-dialog').waitFor({state:'visible'});};
 const choose=async name=>{await p.getByRole('option',{name,exact:true}).click();await p.locator('#choice-dialog').waitFor({state:'hidden'});};
 const close=async()=>{await p.locator('#modal [data-action=close-modal]').click();await p.locator('#modal').waitFor({state:'hidden'});};
 try{
  await p.route('**/api/scenes/save',r=>{sent.push(r.request().postDataJSON());return r.fulfill({json:{status:'completed'}})});
  for(const size of [{width:320,height:640},{width:360,height:800},{width:412,height:915},{width:915,height:412},{width:1440,height:1000}]){
   await p.setViewportSize(size);await p.evaluate(()=>{page='home';render()});check('Home fits '+size.width+'×'+size.height,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
   if(size.width<=700)check('All five dock destinations visible at '+size.width,await p.locator('#bottom-nav button').evaluateAll(es=>es.length===5&&es.every(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.bottom<=innerHeight&&r.height>=44;})));
   await p.evaluate(()=>sceneEditor('play'));await p.locator('[data-choice-for=routine-policy]').waitFor();check('Routine has no horizontal overflow at '+size.width,await p.locator('#modal').evaluate(e=>e.scrollWidth<=e.clientWidth+1));
   check('Step tools have 44px touch targets at '+size.width,await p.locator('.step-tools button').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().width>=44&&e.getBoundingClientRect().height>=44)));
   await p.locator('[data-action=add-step]').click();await open('#step-type');check('Picker stays within viewport at '+size.width,await p.locator('#choice-dialog').evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight&&e.scrollWidth<=e.clientWidth+1}));await p.keyboard.press('Escape');check('Escape closes only options at '+size.width,await p.locator('#modal').isVisible()&&!await p.locator('#choice-dialog').isVisible());
   await p.locator('#step-form [type=submit]').scrollIntoViewIfNeeded();check('Step submit remains reachable at '+size.width,await p.locator('#step-form [type=submit]').isVisible());await close();
  }
  await p.setViewportSize({width:412,height:915});await p.evaluate(()=>sceneEditor('play'));await p.locator('#routine-name').fill('Rutina visual beta 8');await p.locator('[data-action=add-step]').click();await open('#step-type');await p.keyboard.press('End');await p.keyboard.press('Enter');check('Keyboard selects the Wait step and updates the real form',await p.locator('#step-type').inputValue()==='wait'&&await p.locator('[name=seconds]').isVisible());await p.locator('[name=seconds]').fill('2.5');await open('#step-type');await choose('Controlar música');await open('[name=target]');await choose('TIDAL directo');await open('[name=action]');await choose('Pausar');await open('#step-type');await choose('Esperar');check('Wait value survives switching to Music and back',await p.locator('[name=seconds]').inputValue()==='2.5');await open('#step-type');await choose('Controlar música');check('Media target/action survive type round trip',await p.locator('[name=target]').inputValue()==='tidal'&&await p.locator('[name=action]').inputValue()==='pause');
  await open('[name=target]');await choose('Teclas de Windows · sin confirmación');await open('[name=action]');const disabled=p.getByRole('option',{name:'Pausar',exact:true});check('Unsupported action is visibly and semantically disabled',await disabled.getAttribute('aria-disabled')==='true');await disabled.click({force:true});check('Clicking disabled option leaves selection unchanged',await p.locator('#choice-dialog').isVisible()&&await p.locator('[name=action]').inputValue()==='toggle');await p.keyboard.press('Escape');
  await open('[name=target]');await choose('TIDAL directo');await open('[name=action]');await choose('Pausar');await p.locator('#step-form [type=submit]').click();check('Adding a step preserves the routine name and prior sequence',await p.locator('#routine-name').inputValue()==='Rutina visual beta 8'&&await p.locator('.routine-step').count()===3);await p.locator('[data-action=step-up][data-index="2"]').click();check('Reorder moves the selected step without rebuilding values',await p.evaluate(()=>routineDraft[1].type==='media'&&routineDraft[1].action==='pause'));await p.locator('#routine-form [type=submit]').click();await p.waitForFunction(()=>!document.querySelector('#modal').open);check('Saved request contains the intended ordered steps',sent.at(-1).name==='Rutina visual beta 8'&&sent.at(-1).steps[1].target==='tidal'&&sent.at(-1).steps.length===3);
  snapshot.apps.push(...Array.from({length:150},(_,i)=>({id:'test-'+i,name:'Aplicación de prueba '+i,symbol:'app',category:'Pruebas',available:true})));await p.evaluate(s=>{state=s;stepEditor(-1,'launch',{type:'launch',appId:'opera',layout:{monitor:'right',mode:'maximized'},ifOpen:'reuse'})},snapshot);await p.locator('[data-choice-for=step-app]').waitFor();check('App picker keeps its application label beside the outer search field',(await p.locator('[data-choice-for=step-app]').getAttribute('aria-label')).startsWith('Aplicación:'));await open('#step-app');await p.locator('#choice-dialog input').fill('prueba 149');check('Long app menu search filters to the intended result',await p.locator('#choice-dialog [role=option]').count()===1);await p.screenshot({path:path.join(dir,'after-search.png')});await p.locator('#choice-dialog input').press('Enter');await p.locator('#choice-dialog').waitFor({state:'hidden'});check('Custom picker updates the native form value',await p.locator('#step-app').inputValue()==='test-149');await open('#step-app');await p.locator('#choice-dialog input').fill('no-match-example');check('Empty search gives feedback and no stale selectable result',await p.locator('.choice-empty').isVisible()&&await p.locator('#choice-dialog [role=option]').count()===0);await p.evaluate(()=>window.eddyBack());check('Android Back hook closes only the picker and restores trigger focus',await p.locator('#modal').isVisible()&&await p.locator('[data-choice-for=step-app]').evaluate(e=>e===document.activeElement));
  await p.locator('#step-app-search').fill('not-a-real-application');await p.waitForFunction(()=>document.querySelector('[data-choice-for=step-app]').textContent.includes('Seleccionar'));check('No-match outer search clears required app and its visible label',await p.locator('#step-app').inputValue()===''&&await p.locator('[data-choice-for=step-app]').innerText().then(t=>t.includes('Seleccionar')));await p.locator('#step-form [type=submit]').click();check('Required hidden select opens a visible correction menu',await p.locator('#choice-dialog').isVisible());await p.keyboard.press('Escape');await p.locator('#step-app-search').fill('Opera');await open('[name=mode]');await choose('Mitad izquierda');await open('[name=ifOpen]');await choose('Enviar otra apertura a la aplicación');await open('#step-type');await choose('Mover una app ya abierta');await open('#step-type');await choose('Abrir aplicación');check('Window layout and opening policy survive custom type menus',await p.locator('[name=mode]').inputValue()==='left-half'&&await p.locator('[name=ifOpen]').inputValue()==='launch');
  await p.locator('#step-app').evaluate(s=>{s.add(new Option('<img src=x onerror="window.injected=true">','html-fixture'));});await open('#step-app');check('Option names are text, never executable HTML',await p.locator('#choice-dialog img').count()===0&&await p.evaluate(()=>window.injected)===undefined);await p.keyboard.press('Escape');check('Enhancement adds one trigger per select without duplicate handlers',await p.locator('#modal select').count()===await p.locator('#modal .choice-trigger').count());await close();
  await p.emulateMedia({reducedMotion:'reduce'});await p.evaluate(()=>{state.media.tidal.state='playing';page='music';render()});check('Reduced motion disables decorative animation',await p.locator('.vinyl').evaluate(e=>getComputedStyle(e).animationName)==='none');
  await p.evaluate(()=>{page='scenes';render();sceneEditor('play');document.documentElement.style.zoom='1.5'});await p.locator('[data-choice-for=routine-policy]').click();check('Picker remains scrollable with 150% zoom',await p.locator('#choice-dialog').evaluate(e=>e.clientHeight>0&&e.scrollWidth<=e.clientWidth+1));await p.keyboard.press('Escape');await close();await p.evaluate(()=>document.documentElement.style.zoom='1');
  await p.evaluate(()=>{sceneEditor('play');routineDraft=Array.from({length:18},()=>({type:'wait',seconds:1}));routineEditor()});await p.locator('[data-action=add-step]').scrollIntoViewIfNeeded();await p.locator('[data-action=add-step]').click();check('New step from a long routine starts at the top without hiding its header',await p.locator('#modal').evaluate(e=>e.scrollTop===0&&document.querySelector('#modal-title').getBoundingClientRect().top>=e.getBoundingClientRect().top));await close();
  check('No JavaScript runtime errors',errors.length===0);
  const hashes=JSON.parse(cp.execFileSync(path.join(root,'.build/venv/Scripts/python.exe'),['-c','import json;from scripts.package_evidence import product_sources;print(json.dumps(product_sources()))'],{cwd:root,encoding:'utf8'}));fs.writeFileSync(path.join(root,'artifacts/beta8-visual-tests.json'),JSON.stringify({passed:true,count:checks.length,checks,sourceHashes:hashes,scope:'Actual production UI in Edge, synthetic PC state/transport. Responsive, keyboard, picker, routine values, XSS, reduced motion; Android physical checks separate.'},null,2));
 }finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
