'use strict';
const backupURL='https://github.com/eddyorlandotp/eddy-deck/releases';
const capability=name=>state?.capabilities?.[name]===true;
const openPolicy=(value='reuse')=>`<label class="field"><span>Si la aplicación ya está abierta</span><select name="ifOpen"><option value="reuse" ${value!=='launch'?'selected':''}>Usar su ventana existente</option><option value="launch" ${value==='launch'?'selected':''}>Enviar otra apertura a la aplicación</option></select></label><p class="hint">Con varias ventanas, elige una en Mi PC para moverla. Una URL siempre se envía al navegador. Cada app decide si admite otra ventana.</p>`;
const betaCardEditor=cardEditor;cardEditor=function(app,card){betaCardEditor(app,card);if(capability('windowControls'))$('#card-form .modal-actions').insertAdjacentHTML('beforebegin',openPolicy(card?.ifOpen));};
const betaStepEditor=stepEditor;stepEditor=function(index=-1,type,editing){betaStepEditor(index,type,editing);const s=editing||routineDraft[index];if($('#step-type').value==='launch'&&capability('windowControls'))$('#step-form .modal-actions').insertAdjacentHTML('beforebegin',openPolicy(s?.ifOpen));};
const betaRepairSection=repairSection;repairSection=function(){return betaRepairSection().replace('Reparar receptor de la PC','Reiniciar conexión de Windows').replace('</section>',`<div class="repair-actions"><button class="secondary" data-action="check-installation">Comprobar archivos de Windows</button><button class="secondary" data-action="repair-files">Reparar archivos de Eddy Deck</button><button class="text-button" data-action="user-manual">Manual de usuario</button><button class="text-button" data-action="open-backup">Versiones e instaladores en GitHub</button>${native?'<button class="text-button" data-action="save-documentation">Guardar manual e informes</button>':''}<button class="text-button" data-action="pending-records">Revisar órdenes recordadas</button></div><p class="hint">Si Windows no conecta, usa allí el acceso directo «Eddy Deck - Reparar». La reparación de archivos funciona con una copia local verificada.</p></section>`);};
const betaRender=render;render=function(){betaRender();if(!state)return;
  if(typeof EDDY_CLIENT_VERSION==='string'&&state.version!==EDDY_CLIENT_VERSION)$('#content').insertAdjacentHTML('afterbegin',`<div class="notice"><strong>Las versiones son distintas</strong><p>Este panel: ${esc(EDDY_CLIENT_VERSION)} · Windows: ${esc(state.version)}. Actualiza ambos con la misma entrega. Los controles que esta PC todavía no admite estarán desactivados.</p><button class="text-button" data-action="open-backup">Abrir respaldo de actualizaciones</button>${native?'<button class="text-button" data-action="installer-guide">Usar el instalador de este celular</button>':''}</div>`);
  if(!capability('fileRepair'))for(const el of document.querySelectorAll('[data-action="check-installation"],[data-action="repair-files"]')){el.disabled=true;el.title='Actualiza Eddy Deck en Windows para usar este control.';}
  if(['pc','scenes'].includes(page)&&capability('queuePause')){
    const bar=[...$('#content').querySelectorAll('.section-bar')].find(el=>el.querySelector('h2')?.textContent==='Cola y resultados');
    const html=`<div class="notice"><strong>${state.queue?.paused?'Cola en pausa':'Cola activa'}</strong> · ${state.queue?.waiting||0} pendientes <button class="secondary" data-action="queue-pause">${state.queue?.paused?'Reanudar':'Pausar siguientes tareas'}</button><p class="hint">La rutina o tarea que ya comenzó termina. La música y Cancelar siguen disponibles.</p></div>`;
    (bar||$('#content')).insertAdjacentHTML(bar?'afterend':'beforeend',html);
  }
  if(page==='pc'){
    $('#content').insertAdjacentHTML('afterbegin',`<p class="notice" id="availability-status"><strong>Disponibilidad:</strong> ${state.keepAwake?.active?'Eddy Deck mantiene Windows despierto mientras está en ejecución. El monitor puede apagarse.':'Windows no confirma la protección contra suspensión automática.'} ${state.keepAwake?.error?`<span>La solicitud falló: ${esc(state.keepAwake.error)}${Number.isInteger(state.keepAwake.errorCode)?' · código '+esc(state.keepAwake.errorCode):''}. Eddy Deck volverá a intentarlo.</span>`:''} ${native?'La pantalla de este celular permanece encendida mientras Eddy Deck está en primer plano.':''}</p>`);
    if(state.displayWarning)$('#content').insertAdjacentHTML('afterbegin',`<p class="notice">${esc(state.displayWarning)}</p>`);
    if(capability('windowControls'))for(const button of document.querySelectorAll('[data-action="window-layout"]')){button.dataset.action='window-controls';button.textContent='Controlar';const w=state.windows.find(w=>w.id===button.dataset.id);if(w?.protected)button.parentElement.querySelector('small').append(' · protegida');}
  }
};
function windowControls(w){if(!w)throw Error('La ventana cambió o se cerró. Actualiza Mi PC.');showModal('Controlar ventana',`<p class="subtitle">${esc(w.title)}</p><p class="hint">${esc(w.process)}${w.protected?' · protegida de órdenes de Eddy Deck':''}</p><div class="repair-actions"><button class="secondary" data-action="window-layout" data-id="${esc(w.id)}" ${w.protected?'disabled':''}>Pantalla y tamaño</button><button class="secondary" data-action="window-quick" data-id="${esc(w.id)}" data-mode="${w.minimized?'restore':'minimized'}" ${w.protected?'disabled':''}>${w.minimized?'Restaurar':'Minimizar'}</button><button class="secondary" data-action="window-protect" data-id="${esc(w.id)}">${w.protected?'Quitar protección':'Proteger de Eddy Deck'}</button><button class="secondary" data-action="window-close" data-id="${esc(w.id)}" ${w.protected?'disabled':''}>Cerrar normalmente</button></div><p class="hint">La protección dura mientras esta ventana y el receptor sigan abiertos. Evita movimientos, cierres y finalizaciones desde Eddy Deck; no bloquea Windows ni la propia aplicación.</p><details><summary>Si la aplicación no responde</summary><p>Finalizar el proceso puede perder cambios sin guardar y cerrar todas las ventanas de ese proceso. No se permite para Windows, Eddy Deck ni procesos que no se identificaron en el catálogo.</p><button class="secondary danger-text" data-action="window-force" data-id="${esc(w.id)}" ${w.protected?'disabled':''}>Preparar finalización…</button></details>`);}
const betaPerform=perform;perform=async function(action,el){
  const wid=el?.dataset.id;
  switch(action){
    case 'window-controls':return windowControls(state.windows.find(w=>w.id===wid));
    case 'window-protect':{const w=state.windows.find(w=>w.id===wid);toast((await api('/api/windows/protect',{windowId:wid,protected:!w.protected})).message);await load(true);return windowControls(state.windows.find(w=>w.id===wid));}
    case 'window-quick':toast((await api(el.dataset.mode==='restore'?'/api/windows/restore':'/api/windows/move',{windowId:wid,layout:{monitor:'keep',mode:el.dataset.mode,missing:'stop'}})).message);$('#modal').close();await load(true);return;
    case 'window-close':showModal('Cerrar normalmente',`<p>Se pide a la aplicación que cierre esta ventana. Si necesita guardar un documento o confirmar algo, atiéndela en Windows.</p><div class="modal-actions"><button class="secondary" data-action="close-modal">Volver</button><button class="primary" data-action="window-close-confirm" data-id="${esc(wid)}">Pedir cierre</button></div>`);return;
    case 'window-close-confirm':toast((await api('/api/windows/close',{windowId:wid,confirm:true})).message);$('#modal').close();await load(true);return;
    case 'window-force':{const r=await api('/api/windows/terminate/prepare',{windowId:wid});showModal('Finalizar '+esc(r.process),`<p>Se terminará el proceso identificado y todas sus ventanas. Se pueden perder cambios sin guardar. La confirmación vence en 20 segundos.</p><div class="modal-actions"><button class="secondary" data-action="close-modal">Volver</button><button class="primary danger" data-action="window-force-confirm" data-challenge="${esc(r.challenge)}">Sí, finalizar este proceso</button></div>`);return;}
    case 'window-force-confirm':toast((await api('/api/windows/terminate/confirm',{challenge:el.dataset.challenge})).message);$('#modal').close();await load(true);return;
    case 'queue-pause':toast((await api('/api/jobs/pause',{paused:!state.queue?.paused})).message);await load(true);return;
    case 'check-installation':{const r=await api('/api/installation/check',{});showModal('Comprobación de Eddy Deck',`<p>${esc(r.message)}</p>${r.files?`<p>${r.files} archivos verificados · ${esc(r.version)}</p>`:''}`);return;}
    case 'repair-files':showModal('Reparar archivos de Eddy Deck',`<p>Se comprueba la firma de la copia local y se reinstalan los archivos de Eddy Deck. Se interrumpen sus tareas pendientes; se conservan botones, rutinas y conexiones. No reinicia Windows ni cierra tus otras aplicaciones.</p><p>Si el receptor ya no responde, abre en Windows «Eddy Deck - Reparar». Si la copia también falla, usa la descarga de GitHub.</p><div class="modal-actions"><button class="secondary" data-action="close-modal">Volver</button><button class="primary" data-action="confirm-repair-files">Reparar archivos</button></div>`);return;
    case 'confirm-repair-files':{const r=await api('/api/installation/repair',{confirm:true});$('#modal').close();toast(r.message);return;}
    case 'user-manual':showModal('Manual de usuario',typeof EDDY_MANUAL==='string'?EDDY_MANUAL:'<p>El manual también está en tu carpeta de Eddy Deck y en GitHub.</p>');return;
    case 'open-backup':if(native)await nativeCall('openBackup');else window.open(backupURL,'_blank','noopener,noreferrer');return;
    case 'save-documentation':await nativeCall('exportDocumentation');return;
    case 'pending-records':{let count;try{const p=JSON.parse(localStorage.getItem('eddy-pending-'+(native?bootstrap?.pcId:'local'))||'{}');count=Object.keys(p).length;}catch(_){count='un registro ilegible';}showModal('Órdenes recordadas',`<p>Hay ${esc(count)} órdenes guardadas sin respuesta confirmada. Revisa «Mi PC → Cola y resultados» antes de repetir acciones.</p><p>Limpiar este registro no cancela las acciones de Windows. Una acción repetida después de limpiarlo podría ejecutarse de nuevo.</p><div class="modal-actions"><button class="secondary" data-action="close-modal">Conservar</button><button class="secondary" data-action="clear-pending-records">Ya revisé los resultados: limpiar</button></div>`);return;}
    case 'clear-pending-records':localStorage.removeItem('eddy-pending-'+(native?bootstrap?.pcId:'local'));$('#modal').close();toast('Registro local limpiado. Las tareas de Windows se conservan.');return;
    case 'confirm-import':{const r=await api('/api/backup/import',{profile:window.importProfile});$('#modal').close();await load(true);toast(r.message);return;}
  }
  return betaPerform(action,el);
};
